#!/bin/bash

[[ "${-}" != *i* ]] && return

HISTCONTROL=ignoreboth
HISTFILE="${HOME}/.histfile"
HISTSIZE=1024
HISTFILESIZE=8192

shopt -s autocd \
  cdspell \
  checkwinsize \
  complete_fullquote \
  expand_aliases \
  extglob \
  extquote \
  histappend \
  histverify \
  interactive_comments \
  no_empty_cmd_completion \
  progcomp \
  progcomp_alias

PS1='\[\033[01;32m\][$?]\[\033[01;35m\][\W]\n\[\033[01;36m\]\$\[\033[00m\] '
PS2='\[\033[01;32m\]+\[\033[00m\] '
printf -v PS3 '\033[01;32m>\033[00m '
PS4='\[\033[01;31m\]!\[\033[00m\] '

[[ -f ~/.shrc ]] && . ~/.shrc
[[ -f /usr/share/bash-completion/bash_completion ]] && . /usr/share/bash-completion/bash_completion

set +H -o emacs

export GPG_TTY="$(tty)"

[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"                   # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion
